name: Create version tag

on:
  push:
    branches: [master]
    paths: [package.json]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_CREATE_TAG_TOKEN}}
          tag_prefix: v
